### ISSUE TITLE
Add support for merged virtual pins

### ISSUE THREAD

**Issue by ComputerAided** [vshymanskyy/blynk-library-python#13]
When using the zeRGBa widget in merge mode, three separate calls to the `blynk.VIRTUAL_WRITE` function are made. Make the `VIRTUAL_WRITE` wrapper pass the value as a tuple or list to the handler function.

```
@blynk.VIRTUAL_WRITE(0)
def zeRGBa(value):
    r = value[0]
    g = value[1]
    b = value[2]

    # Do stuff
```

**Comment by thalesvon** [comment]
Any updates on this issue? I couldn't parse each separete value on my code.

**Comment by vshymanskyy** [comment]
@thalesvon I'm preparing an update, and will re-check this - I'm sure it worked before.
Thanks for your patience.

**Comment by andywarburton** [comment]
If you could implement this it would be super handy... I imagine a common thing people will want to do is control neopixel style lights using Blynk and this would make that job a ton easier.

**Comment by mattbrailsford** [comment]
@vshymanskyy was this fixed in the Major Rewrite commit of Nov 4th? 3497c4c4d4f467fa098ce03180bc0cfcf9c9af7a

**Comment by vshymanskyy** [comment]
This will be verified before the upcoming 0.2.0 release.
Thanks!

**Comment by ComputerAided** [comment]
Thanks for adding this! I can't wait to use it in my project.

**Comment by vshymanskyy** [comment]
Verified in the master branch

**Comment by vshymanskyy** [comment]
v0.2.0 is released and available via pip:
https://github.com/vshymanskyy/blynk-library-python/releases/latest
