### ISSUE TITLE
disconnected after 30 seconds on ESP32

### ISSUE THREAD

**Issue by hznupeter** [vshymanskyy/blynk-library-python#17]
I uploaded the [02_virtual_read](https://github.com/vshymanskyy/blynk-library-python/blob/master/examples/02_virtual_read.py) ,it will connect to Blynk app, but after 30 seconds ,it will disconnected. 
I have tried different boards ,but the same result.

**Comment by hznupeter** [comment]
```
import network
import BlynkLib
import time
from mpython import *
wlan = network.WLAN(network.STA_IF)
wlan.active(True)
if not wlan.isconnected():
  print('connecting to network...')
  wlan.connect('Xxxxi_0432', 'xxxxxxxxxxx') 
  while not wlan.isconnected():
    pass
print('network config:', wlan.ifconfig())
BLYNK_AUTH = 'e8d3214523d148a1beacc8022af2273b'
# Initialize Blynk
blynk = BlynkLib.Blynk(BLYNK_AUTH)
while True:
	blynk.run()
	pass
```

**Comment by vshymanskyy** [comment]
v0.2.0 is released and available via pip:
https://github.com/vshymanskyy/blynk-library-python/releases/latest
