### ISSUE TITLE
Make it work with local blink servee

### ISSUE THREAD

**Issue by cheak1974** [vshymanskyy/blynk-library-python#20]
Hi,
I edited your source to make it connect to a local server. This works good. I can also set values but I am unable to retrieve values from the app. 

Maybe I broke something. But connecting to a local instance should be possible as a standard. Also it would be nice to connect own callbacks. I don't like the decorator approach as this is not working when using blynk-python inside instances of my own classes.

**Comment by vshymanskyy** [comment]
Implemented in the master branch

**Comment by vshymanskyy** [comment]
v0.2.0 is released and available via pip:
https://github.com/vshymanskyy/blynk-library-python/releases/latest
