### ISSUE TITLE
Simultaneous VIRTUAL_READ and VIRTUAL_WRITE?

### ISSUE THREAD

**Issue by chrissv** [vshymanskyy/blynk-library-python#21]
I am using the library installed by `pip` on my Raspberry Pi Model 3 B+.
Here is the version information:
```
Name: blynk-library-python
Version: 0.1.3
Summary: Blynk library
Home-page: http://www.blynk.cc
Author: Volodymyr Shymanskyy
Author-email: vshymanskyi@gmail.com
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires:
```

Looking at the library code, it appears that when `VIRTUAL_READ` is used on a virtual pin, it sets the write callback to None. Similarly, when using `VIRTUAL_WRITE` it sets the read callback to None.

I have a need of both a read and write callback on the same virtual pin.
Is there a way to achieve this?

**Comment by vshymanskyy** [comment]
With the 0.2.0 update, this should work as expected

**Comment by chrissv** [comment]
Wonderful! What is the timeframe you anticipate for the 0.2.0 update?

**Comment by vshymanskyy** [comment]
v0.2.0 is released and available via pip:
https://github.com/vshymanskyy/blynk-library-python/releases/latest
