### ISSUE TITLE
Unexpected command: 41

### ISSUE THREAD

**Issue by iker190** [vshymanskyy/blynk-library-python#28]
I'm getting "Unexpected command: 41" error each time I start my program, sometimes the program starts correctly but it stops after a few hours (~2h). After that if I try to start the program again I get the error.
I also get the same error when I try the readme example. I tried on a linux desktop computer and on a raspberry pi. 
I can see that command 41 is not implemented yet but I haven't seen anyone with my same issue. Could be a problem with my home network? What does the 41 command do?
Thank you

**Comment by vshymanskyy** [comment]
Which hardware/os do you have? Please also provide your script code.

**Comment by iker190** [comment]
Hi, I'm using a raspberry pi 3 running Raspbian 9 stretch and Python 3.5.3.
Here is my code:
```Python
import serial
import yaml
import BlynkLib
from time import sleep

MENU = [[1], [2, 3], [4], [5], [2], [3], [1, 2, 3, 4, 5]]
BLYNK_AUTH = 'my token'
serial = serial.Serial("/dev/ttyACM0", 9600, timeout=1)
blynk = BlynkLib.Blynk(BLYNK_AUTH)

def read_config_file(conf=2):
    with open("config.yaml", "r") as codes_file:
        config = yaml.load(codes_file)
        if conf == 2:
            return config
        if conf == 1:
            return config["configuration"]
        if conf == 0:
            return config["persianas"]
        
def send_command(cmd):
    if not lock:
        for blind in current_blind:
            command = blind_config[blind-1][cmd]
            print(command)
            serial.write(command.encode())
            sleep(0.1)
            serial.write(command.encode())
            sleep(0.5)
        
@blynk.VIRTUAL_WRITE(0)
def lock_handler(status):
    global lock 
    lock = int(status[0])
        
@blynk.VIRTUAL_WRITE(1)
def blind_handler1(sel):
    blind_read_handler1()
    sel = int(sel[0])
    global current_blind
    current_blind = []
    for i in range(len(MENU[sel-1])):
        current_blind.append(MENU[sel-1][i])

@blynk.VIRTUAL_WRITE(3)
def blind_handler2(sel):
    blind_read_handler2()
    sel = int(sel[0])+4
    global current_blind
    current_blind = []
    for i in range(len(MENU[sel-1])):
        current_blind.append(MENU[sel-1][i])
        
@blynk.VIRTUAL_READ(3)
def blind_read_handler2():
    blynk.virtual_write(1, 0)
    
@blynk.VIRTUAL_READ(1)
def blind_read_handler1():
    blynk.virtual_write(3, 0)
                
@blynk.VIRTUAL_WRITE(2)
def command_handler(cmd):
    cmd = int(cmd[0])
    if cmd == 1:
        send_command("up")
    if cmd == 2:
        send_command("down")
    if cmd == 3:
        send_command("stop")
    
full_config = read_config_file()
blind_config = full_config["persianas"]
setting_config = full_config["configuration"]
current_blind = []
lock = 1

while True:
    blynk.run()
```

**Comment by iker190** [comment]
It's been working now for a week without any error. The program remains unchanged.

**Comment by jraiwi** [comment]
I am facing the same issue and not solved.
I am using NodeMCU ESP8266 and micropython.
I get the error Unexpected command:  41 when using blynk:

"""
Blynk is a platform with iOS and Android apps to control
Arduino, Raspberry Pi and the likes over the Internet.
You can easily build graphic interfaces for all your
projects by simply dragging and dropping widgets.

  Downloads, docs, tutorials: http://www.blynk.cc
  Sketch generator:           http://examples.blynk.cc
  Blynk community:            http://community.blynk.cc
  Social networks:            http://www.fb.com/blynkapp
                              http://twitter.com/blynk_app

This example shows how to initialize your ESP8266/ESP32 board
and connect it to Blynk.

Don't forget to change WIFI_SSID, WIFI_PASS and BLYNK_AUTH ;)
"""

import BlynkLib
import network
import machine

WIFI_SSID = 'HamzaJraiwi'
WIFI_PASS = '123123123'

BLYNK_AUTH = 'TKMRZpNuGY28sLQt3gJ_uFUt30RawsZU'

print("Connecting to WiFi...")
wifi = network.WLAN(network.STA_IF)
wifi.active(True)
wifi.connect(WIFI_SSID, WIFI_PASS)
while not wifi.isconnected():
    pass

print('IP:', wifi.ifconfig()[0])

print("Connecting to Blynk...")
blynk = BlynkLib.Blynk(BLYNK_AUTH)

@blynk.on("connected")
def blynk_connected(ping):
    print('Blynk ready. Ping:', ping, 'ms')

def runLoop():
    while True:
        blynk.run()
        machine.idle()

# Run blynk in the main thread:
runLoop()

# Or, run blynk in a separate thread (unavailable for esp8266):
#import _thread
#_thread.stack_size(5*1024)
#_thread.start_new_thread(runLoop, ())


# Note:
# Threads are currently unavailable on some devices like esp8266
# ESP32_psRAM_LoBo has a bit different thread API:
# _thread.start_new_thread("Blynk", runLoop, ())

**Comment by jraiwi** [comment]
I am facing the same issue and not solved.
I am using NodeMCU ESP8266 and micropython.
I get the error Unexpected command: 41 when using blynk:
Below is my code ....


import BlynkLib
import network
import machine

WIFI_SSID = 'HamzaJraiwi'
WIFI_PASS = '<passwd>'

BLYNK_AUTH = '<auth>'

print("Connecting to WiFi...")
wifi = network.WLAN(network.STA_IF)
wifi.active(True)
wifi.connect(WIFI_SSID, WIFI_PASS)
while not wifi.isconnected():
pass

print('IP:', wifi.ifconfig()[0])

print("Connecting to Blynk...")
blynk = BlynkLib.Blynk(BLYNK_AUTH)

@blynk.on("connected")
def blynk_connected(ping):
print('Blynk ready. Ping:', ping, 'ms')

def runLoop():
while True:
blynk.run()
machine.idle()

Run blynk in the main thread:
runLoop()
