### ISSUE TITLE
Unexpected command:  41 on blynk

### ISSUE THREAD

**Issue by jraiwi** [vshymanskyy/blynk-library-python#43]
I get the error Unexpected command:  41 every time I run the below python script ...
Can anyone help?

import BlynkLib
import network
import machine

WIFI_SSID = 'HamzaJraiwi'
WIFI_PASS = 'pass'

BLYNK_AUTH = 'auth'

print("Connecting to WiFi...")
wifi = network.WLAN(network.STA_IF)
wifi.active(True)
wifi.connect(WIFI_SSID, WIFI_PASS)
while not wifi.isconnected():
    pass

print('IP:', wifi.ifconfig()[0])

print("Connecting to Blynk...")
blynk = BlynkLib.Blynk(BLYNK_AUTH)

@blynk.on("connected")
def blynk_connected(ping):
    print('Blynk ready. Ping:', ping, 'ms')

def runLoop():
    while True:
        blynk.run()
        machine.idle()

# Run blynk in the main thread:
runLoop()

**Comment by Lennyz1988** [comment]
I have the same issue. It has something to do with the DNS not properly being translated in an ip adress.

Use:
`blynk = BlynkLib.Blynk(BLYNK_AUTH,
                       server='139.59.206.133', # set server address
                       port=80,              # set server port
                       heartbeat=30,           # set heartbeat to 30 secs
                       log=print               # use print function for debug logging
                       )`

instead of

`blynk = BlynkLib.Blynk(BLYNK_AUTH)`

**Comment by vshymanskyy** [comment]
This will be fixed with the next update
