### ISSUE TITLE
Python3.5 and BlynkLib v0.2.0: IndexError: list index out of range

### ISSUE THREAD

**Issue by Vadzz-K** [vshymanskyy/blynk-library-python#44]
Hey. Until the last moment I used the library version 1.3. I wrote a simple Python 3.5 script to send some data to a local blynk server. Everything worked (and works) super. I decided to try BlynkLib for Python version 2.0 (and the Blynk timer library) and I can’t understand what’s the matter. When a mobile application connects, Python script stopped with an Error:
`  File "/usr/local/lib/python3.5/dist-packages/BlynkLib.py", line 252, in run
    self.process(data)
  File "/usr/local/lib/python3.5/dist-packages/BlynkLib.py", line 213, in process
    self.emit("int_"+args[1], args[2:])
IndexError: list index out of range`

Same error - after mobile application was closed (disconnected from local server).
If the application is active and I run the python script, then the data arrives, the widgets work. I close the application - the python script stops with an error.
My system: Raspberry Pi3, Blynk local Server (0.41.12-java8), Python 3.5

**Comment by Lennyz1988** [comment]
It has probably to do with this this typo in the library.

https://github.com/vshymanskyy/blynk-library-python/pull/31/files

**Comment by vshymanskyy** [comment]
Will be fixed in next update
