### ISSUE TITLE
Buttons stop working over time

### ISSUE THREAD

**Issue by ghost** [vshymanskyy/blynk-library-python#47]
I'm making a device to automate humidity/temperature in a little tent. 
I have 3 virtual buttons. When I run my program, just at the start they work as expected.
If my sensor get a given humidity value, it calls a function to increase it, after this point the buttons stop working

I'm using python 3.7 on a raspberry pi

**Comment by vshymanskyy** [comment]
Not enough info provided. Probably duplicate of #36
