### ISSUE TITLE
Attribute Error: 'Blynk' Object has no attribute 'handle_event'

### ISSUE THREAD

**Issue by dinesh-parmar** [vshymanskyy/blynk-library-python#48]
So, I was trying to control Servo Motor using Blynk App. I used Python coding on Raspberry Pi to connect to the GPIO pins. I'm getting the above-stated error whereas I wrote the exact syntax as mentioned on our Git.

**Comment by EricHier** [comment]
Did you solve the issue? I would like to use GPIO on the Raspberry Pi as well.

**Comment by dinesh-parmar** [comment]
> Did you solve the issue? I would like to use GPIO on the Raspberry Pi as well. 

Nope  The Library isn't working that Properly. Use HTTP API using Python's Request Library.

**Comment by vshymanskyy** [comment]
Not enough info to understand what's wrong here.
