### ISSUE TITLE
GPIO on ESP8266

### ISSUE THREAD

**Issue by segallis** [vshymanskyy/blynk-library-python#50]
In my blynk app I am only able to get virtual pins working with this library, the actual GPIO - GPIO2 is connected to the onboard LED, for example - do not respond to blynk app buttons.  Are the GPIO implemented in this library, or just the virtual pins?

**Comment by vshymanskyy** [comment]
Currently there are only virtual pins. On Blynk 2.0 Analog/Digital pins are not yet available, but when they are - I'll try to provide some examples
