### ISSUE TITLE
error on blynk.on

### ISSUE THREAD

**Issue by defaliz** [vshymanskyy/blynk-library-python#52]
Hi,
i try examples , each time blynk.on is used i have the same error

" @blynk.on("connected")
TypeError: on() takes exactly 3 arguments (2 given)"

why ?, thanks for replies
regards

**Comment by defaliz** [comment]
i answer myself..
i've made a mistake..
it's works when examples are in the same place than BlynkLib.py

have a good day

**Comment by ratheeshbr** [comment]
Is there any way to clear this error

**Comment by ratheeshbr** [comment]
TypeError: my_write_handler() takes exactly 1 argument (0 given)

**Comment by ploebb** [comment]
There are two methods defined in BlynkLib.py: `def on(self, evt, func):` and `def ON(blynk, evt):`
In the examples, the lower case is used where the upper case ON should be used (bug?)!

So for example, change
`@blynk.on("connected")` to `@blynk.ON("connected")` and it should work.
