### ISSUE TITLE
Library support for ESP32 Micro Python

### ISSUE THREAD

**Issue by Tarun75** [vshymanskyy/blynk-library-python#54]
Hi, Can you please also provide library for ESP32 over Micro python language. I am currently using old Blynk.mpy library for old cloud server. Can that be tweaked in for new cloud connection and accepting template id. I suppose some part of code will change. Please help.

**Comment by Tarun75** [comment]
can u publish more examples please for virtual pin read and write.

**Comment by vshymanskyy** [comment]
This library should work on MicroPython without issues. Also examples are provided already
