### ISSUE TITLE
Over the air update

### ISSUE THREAD

**Issue by Tarun75** [vshymanskyy/blynk-library-python#55]
Hi,
Any news on OTA update for Blynk IoT micro python library for ESP32.

**Comment by vshymanskyy** [comment]
OTA is planned for Raspberry Pi only.

**Comment by Tarun75** [comment]
Hi Vshymanskyy

Rpi is expensive proposition for IoT hardware for home automation
segment,whereas ESP32 is better cost wise and from deployment point of
view. It will be more value add if OTA is developed for ESP32.
I request you to relook at this aspect.

**Comment by vshymanskyy** [comment]
it could work for PSRAM-enabled modules
