### ISSUE TITLE
I can't burn library on esp8266

### ISSUE THREAD

**Issue by lifelimited** [vshymanskyy/blynk-library-python#8]
I burn library on esp8266

cmd show memory allocation failed

how I can do ?

thank you

**Comment by vshymanskyy** [comment]
It means you can't do this with micropython ATM. I recommend switching to ESP32

**Comment by vshymanskyy** [comment]
@lifelimited I was able to run Blynk on ESP8266.
https://github.com/vshymanskyy/blynk-library-python/releases/latest
